name: iboxpay

on:
    workflow_dispatch:
    schedule:
      - cron: "*/30 * * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: iboxpay

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【笑谱】'
        run: |
          node Task/iboxpay.js
        env:
          XP_refreshTOKEN: ${{ secrets.XP_refreshTOKEN}}
          XP_live: ${{ secrets.XP_live }}
          XP_CASH: ${{ secrets.XP_CASH}}
          XP_phone: ${{ secrets.XP_phone}}
          XP_sms: ${{ secrets.XP_sms}}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
