name: youth.js

on:
    workflow_dispatch:
    schedule:
      - cron: "10 */1 * * *"
    watch:
      types: [started]
    repository_dispatch:
      types: youth.js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【中青阅读】'
        run: |
          node Task/youth.js
        env:
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          YOUTH_HEADER: ${{ secrets.YOUTH_HEADER}}
          YOUTH_ARTBODY: ${{ secrets.YOUTH_ARTBODY}}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME}}
